org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# Mapbox secret download token — get from https://account.mapbox.com/access-tokens/
# Create a token with scope "DOWNLOADS:READ" and paste it here
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoiZ2JyaWRlIiwiYSI6ImNtbWRrOWtvYjAzeGcycnM1OHg2c3BwbGUifQ.2cwq5a2OFpjCdYaphbHubg
