// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb3nNGrN3mNgMIqOlfrkMDifgqH4SO4TU',
    appId: '1:560604047926:web:e0df0e24e33dae42ab4697',
    messagingSenderId: '560604047926',
    projectId: 'gb-ride-a591a',
    authDomain: 'gb-ride-a591a.firebaseapp.com',
    storageBucket: 'gb-ride-a591a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqhXVgwZvsUZtBaxDJWgPh0E5mEaaS2hw',
    appId: '1:560604047926:android:0d59529e23ad976cab4697',
    messagingSenderId: '560604047926',
    projectId: 'gb-ride-a591a',
    storageBucket: 'gb-ride-a591a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpEFB3wEXx2ATJ6ozoBNVvsAjgsMJ3dqQ',
    appId: '1:560604047926:ios:183b801c2bbae26aab4697',
    messagingSenderId: '560604047926',
    projectId: 'gb-ride-a591a',
    storageBucket: 'gb-ride-a591a.firebasestorage.app',
    iosBundleId: 'com.example.gbRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpEFB3wEXx2ATJ6ozoBNVvsAjgsMJ3dqQ',
    appId: '1:560604047926:ios:183b801c2bbae26aab4697',
    messagingSenderId: '560604047926',
    projectId: 'gb-ride-a591a',
    storageBucket: 'gb-ride-a591a.firebasestorage.app',
    iosBundleId: 'com.example.gbRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb3nNGrN3mNgMIqOlfrkMDifgqH4SO4TU',
    appId: '1:560604047926:web:778f6f21119b2e01ab4697',
    messagingSenderId: '560604047926',
    projectId: 'gb-ride-a591a',
    authDomain: 'gb-ride-a591a.firebaseapp.com',
    storageBucket: 'gb-ride-a591a.firebasestorage.app',
  );
}
