// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-AgqQ1a0sLORWELs5JOtXnjAUGPkQrsc',
    appId: '1:664347806856:web:0f764be724dac6167e633d',
    messagingSenderId: '664347806856',
    projectId: 'gbride-01',
    authDomain: 'gbride-01.firebaseapp.com',
    storageBucket: 'gbride-01.firebasestorage.app',
    measurementId: 'G-W811068JXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAehLD7H0gEnObartkJSWc7Wyy1kE7Kvxo',
    appId: '1:664347806856:android:473917b9efea7aa07e633d',
    messagingSenderId: '664347806856',
    projectId: 'gbride-01',
    storageBucket: 'gbride-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChAMMqDfQh2GRDApSOuaKAmLSVSvu1wE0',
    appId: '1:664347806856:ios:a9bee1a8c607b7377e633d',
    messagingSenderId: '664347806856',
    projectId: 'gbride-01',
    storageBucket: 'gbride-01.firebasestorage.app',
    iosBundleId: 'com.example.gbRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChAMMqDfQh2GRDApSOuaKAmLSVSvu1wE0',
    appId: '1:664347806856:ios:a9bee1a8c607b7377e633d',
    messagingSenderId: '664347806856',
    projectId: 'gbride-01',
    storageBucket: 'gbride-01.firebasestorage.app',
    iosBundleId: 'com.example.gbRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-AgqQ1a0sLORWELs5JOtXnjAUGPkQrsc',
    appId: '1:664347806856:web:12525bdc85c13e097e633d',
    messagingSenderId: '664347806856',
    projectId: 'gbride-01',
    authDomain: 'gbride-01.firebaseapp.com',
    storageBucket: 'gbride-01.firebasestorage.app',
    measurementId: 'G-BVX4KVNS3D',
  );
}
